site_name: Industry Toolkit
site_description: >-
  The Industry Toolkit is a collection of assets that enable application development and support teams to deliver business value to Industry 4.0 partners and clients. The toolkit includes assets like Ansible artifacts, code patterns, tutorials, reference architectures and best practices.
site_url: https://remkohdev.github.io/industry-toolkit/
site_author: IBM Build Labs Industry
repo_name: ""
repo_url: https://github.com/remkohdev/industry-toolkit
docs_dir: docs
site_dir: public
edit_uri: edit/main/docs

theme:
    name: material
    logo: images/cloudnativetoolkit.png
    favicon: images/cloudnativetoolkit.png
    palette:
      scheme: default
      primary: black
    font:
      text: IBM Plex Sans
      code: IBM Plex Mono
    language: en
    custom_dir: overrides
    features:
#      - navigation.tabs
      - navigation.instant
      - navigation.tracking
#      - navigation.tabs.sticky
#      - navigation.top
use_directory_urls: true
plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
  - redirects:
      redirect_maps:
        'tools': 'overview/overview.md'

markdown_extensions:
  - attr_list
  - admonition
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.details
extra_css:
    - css/extra.css
    - css/toolkit-code.css
extra:
  generator: false
copyright: Copyright © 2021 Cloud-Native Toolkit
google_analytics: ['UA-153689700-1', 'cloudnativetoolkit.dev']
nav:
  - Home: index.md
  - Overview:
    - What is the Industry Toolkit: overview/overview.md
  - Use Cases:
    - Edge Data Gateway: use-cases/data-edge-gateway.md
  - Guides:
    - ODI Pipeline: guides/odi-pipeline-tutorial.md 
